const express = require('express');
const cors = require('cors');
const { Pool } = require('pg');
const path = require('path');
const fs = require('fs');


const dataDir = path.join(__dirname, 'data');

if (!fs.existsSync(dataDir)) {
  fs.mkdirSync(dataDir, { recursive: true });
}

const app = express();

const PORT = process.env.PORT || 3000;

const  pool  = new Pool({
  connectionString: process.env.DATABASE_URL,
  ssl: process.env.NODE_ENV === 'production'
    ? { rejectUnauthorized: false }
    : false
});

app.use(cors());

app.use(
  express.json({
    limit: '1mb'
  })
);

app.use(
  express.static(
    path.join(__dirname, 'public')
  )
);

/* ================= DATABASE ================= */

async function initDatabase() {

  await pool.query(`
    CREATE TABLE IF NOT EXISTS profile (
      id INTEGER PRIMARY KEY CHECK(id=1),
      name TEXT,
      weight REAL,
      height REAL,
      age INTEGER,
      sex TEXT,
      activity REAL
    );

    CREATE TABLE IF NOT EXISTS workout_plans (
      id TEXT PRIMARY KEY,
      name TEXT NOT NULL,
      sort_order INTEGER DEFAULT 0
    );

    CREATE TABLE IF NOT EXISTS exercises (
      id TEXT PRIMARY KEY,
      plan_id TEXT NOT NULL,
      name TEXT NOT NULL,
      sets INTEGER DEFAULT 3,
      reps TEXT DEFAULT '10',
      load TEXT DEFAULT '—',
      muscle TEXT DEFAULT '',
      instructions TEXT DEFAULT '',
      image_url TEXT DEFAULT '',
      FOREIGN KEY(plan_id)
        REFERENCES workout_plans(id)
        ON DELETE CASCADE
    );

    CREATE TABLE IF NOT EXISTS weight_logs (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      date TEXT NOT NULL,
      weight REAL NOT NULL
    );

    CREATE TABLE IF NOT EXISTS workout_sessions (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      date TEXT NOT NULL,
      plan_id TEXT,
      plan_name TEXT NOT NULL,
      duration INTEGER DEFAULT 0,
      calories INTEGER DEFAULT 0,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS workout_sets (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      session_id INTEGER NOT NULL,
      exercise_name TEXT NOT NULL,
      set_number INTEGER NOT NULL,
      reps INTEGER DEFAULT 0,
      load REAL DEFAULT 0,
      completed INTEGER DEFAULT 0,
      FOREIGN KEY(session_id)
        REFERENCES workout_sessions(id)
        ON DELETE CASCADE
    );
  `);

  await seedLibrary();

  console.log('PostgreSQL: tabelas verificadas/criadas.');

}

/* ================= EXERCISE LIBRARY ================= */

const seed = [

  [
    'Supino reto com halteres',
    'Peito',
    'Deite-se no banco, desça os halteres com controle e empurre mantendo os pés firmes.',
    'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=900&q=80'
  ],

  [
    'Supino inclinado com halteres',
    'Peito',
    'Banco inclinado, escápulas firmes e halteres descendo de forma controlada.',
    'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?auto=format&fit=crop&w=900&q=80'
  ],

  [
    'Crucifixo na polia',
    'Peito',
    'Mantenha leve flexão nos cotovelos e aproxime as mãos à frente do corpo.',
    'https://images.unsplash.com/photo-1598971639058-a4c5c9c3c8c5?auto=format&fit=crop&w=900&q=80'
  ],

  [
    'Desenvolvimento com halteres',
    'Ombros',
    'Empurre os halteres acima da cabeça sem exagerar na extensão lombar.',
    'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=900&q=80'
  ],

  [
    'Elevação lateral',
    'Ombros',
    'Eleve os braços até próximo da linha dos ombros, controlando a descida.',
    'https://images.unsplash.com/photo-1599058917212-d750089bc07e?auto=format&fit=crop&w=900&q=80'
  ],

  [
    'Tríceps na polia',
    'Tríceps',
    'Mantenha os cotovelos próximos ao corpo e estenda os braços sem balançar.',
    'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?auto=format&fit=crop&w=900&q=80'
  ],

  [
    'Rosca martelo',
    'Bíceps',
    'Pegada neutra, cotovelos estáveis e movimento controlado.',
    'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?auto=format&fit=crop&w=900&q=80'
  ],

  [
    'Puxada alta',
    'Costas',
    'Puxe a barra em direção ao peito mantendo o tronco estável.',
    'https://images.unsplash.com/photo-1603287681836-b174ce5074c2?auto=format&fit=crop&w=900&q=80'
  ],

  [
    'Remada na polia',
    'Costas',
    'Puxe em direção ao abdômen, juntando as escápulas sem impulsionar o corpo.',
    'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=900&q=80'
  ],

  [
    'Agachamento livre',
    'Pernas',
    'Desça com controle mantendo o tronco firme e os joelhos acompanhando os pés.',
    'https://images.unsplash.com/photo-1566241142559-40e1dab266c6?auto=format&fit=crop&w=900&q=80'
  ],

  [
    'Stiff',
    'Posterior',
    'Leve o quadril para trás mantendo a coluna neutra e sinta o alongamento posterior.',
    'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?auto=format&fit=crop&w=900&q=80'
  ],

  [
    'Cadeira extensora',
    'Quadríceps',
    'Estenda os joelhos de forma controlada e pause brevemente no topo.',
    'https://images.unsplash.com/photo-1434682881908-b43d0467b798?auto=format&fit=crop&w=900&q=80'
  ]

];

/* ================= LIBRARY SEED ================= */

async function seedLibrary() {
  await pool.query(`
    INSERT INTO workout_plans(
      id,
      name,
      sort_order
    )
    VALUES(
      'LIBRARY',
      'Biblioteca',
      -1
    )
    ON CONFLICT (id) DO NOTHING
  `);

  for (
    const [
      name,
      muscle,
      instructions,
      image
    ] of seed
  ) {

    const id =
      'lib_' +
      name
        .toLowerCase()
        .replace(/[^a-z0-9]+/gi, '_');

    await pool.query(`
      INSERT INTO exercises(
        id,
        plan_id,
        name,
        sets,
        reps,
        load,
        muscle,
        instructions,
        image_url
      )
      VALUES(
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9
      )
      ON CONFLICT (id) DO NOTHING
    `, [
      id,
      'LIBRARY',
      name,
      3,
      '8–12',
      '—',
      muscle,
      instructions,
      image
    ]);
  }

  console.log(
    'Biblioteca de exercícios verificada.'
  );
}

/* ================= HELPERS ================= */

function uid() {

  return (
    Date.now().toString(36) +
    Math.random()
      .toString(36)
      .slice(2, 7)
  );

}

async function getPlans() {
  const result = await pool.query(`
    SELECT *
    FROM workout_plans
    ORDER BY sort_order, id
  `);

  const plans = result.rows;

  for (const p of plans) {
    const exercises = await pool.query(`
      SELECT
        id,
        name AS nome,
        sets AS series,
        reps,
        load AS carga,
        muscle,
        instructions,
        image_url AS "imageUrl"
      FROM exercises
      WHERE plan_id = $1
      ORDER BY id
    `, [p.id]);

    p.exercicios = exercises.rows;
  }

  return plans;
}

async function getState() {
  const profileResult = await pool.query(`
    SELECT
      name,
      weight AS peso,
      height AS altura,
      age AS idade,
      sex,
      activity AS atividade
    FROM profile
    WHERE id = 1
  `);

  const profile = profileResult.rows[0] || null;

  const weightResult = await pool.query(`
    SELECT
      date AS data,
      weight AS peso
    FROM weight_logs
    ORDER BY date
  `);

  const historyResult = await pool.query(`
    SELECT
      id,
      date AS data,
      plan_name AS "diaNome",
      duration,
      calories
    FROM workout_sessions
    ORDER BY date DESC, id DESC
  `);

  const history = historyResult.rows;

  for (const h of history) {
    const setsResult = await pool.query(`
      SELECT
        exercise_name AS nome,
        set_number,
        reps,
        load AS carga,
        completed AS feito
      FROM workout_sets
      WHERE session_id = $1
      ORDER BY set_number
    `, [h.id]);

    h.exercicios = setsResult.rows;
  }

  return {
    plan: await getPlans(),
    weightLog: weightResult.rows,
    profile,
    userName: profile?.name || null,
    lastWorkoutCalories: history[0]?.calories || null,
    workoutHistory: history
  };
}

/* ================= HEALTH ================= */

app.get(
  '/api/health',
  async (req, res) => {
    try {
      await pool.query('SELECT 1');

      res.json({
        ok: true,
        db: 'postgresql'
      });
    } catch (error) {
      res.status(500).json({
        ok: false,
        db: 'postgresql'
      });
    }
  }
);

/* ================= STATE ================= */

app.get(
  '/api/state',
  async (req, res) => {
    try {
      const state = await getState();

      res.json(state);
    } catch (error) {
      console.error('Erro ao buscar estado:', error);

      res.status(500).json({
        error: 'Erro ao buscar dados.'
      });
    }
  }
);

/* ================= EXERCISES ================= */

app.get(
  '/api/exercises',
  async (req, res) => {
    try {
      const q = (req.query.q || '').trim();

      let result;

      if (q) {
        result = await pool.query(`
          SELECT
            id,
            name,
            muscle,
            instructions,
            image_url AS "imageUrl"
          FROM exercises
          WHERE
            plan_id = 'LIBRARY'
            AND name ILIKE $1
          ORDER BY name
          LIMIT 20
        `, [`%${q}%`]);
      } else {
        result = await pool.query(`
          SELECT
            id,
            name,
            muscle,
            instructions,
            image_url AS "imageUrl"
          FROM exercises
          WHERE plan_id = 'LIBRARY'
          ORDER BY name
          LIMIT 50
        `);
      }

      res.json(result.rows);

    } catch (error) {
      console.error('Erro ao buscar exercícios:', error);

      res.status(500).json({
        error: 'Erro ao buscar exercícios.'
      });
    }
  }
);

/* ================= PROFILE ================= */

app.put(
  '/api/profile',
  async (req, res) => {
    try {
      const p = req.body || {};

      await pool.query(`
        INSERT INTO profile(
          id,
          name,
          weight,
          height,
          age,
          sex,
          activity
        )
        VALUES(
          1,
          $1,
          $2,
          $3,
          $4,
          $5,
          $6
        )
        ON CONFLICT(id)
        DO UPDATE SET
          name = EXCLUDED.name,
          weight = EXCLUDED.weight,
          height = EXCLUDED.height,
          age = EXCLUDED.age,
          sex = EXCLUDED.sex,
          activity = EXCLUDED.activity
      `, [
        p.name || '',
        p.peso || null,
        p.altura || null,
        p.idade || null,
        p.sexo || 'M',
        p.atividade || 1.55
      ]);

      res.json(await getState());

    } catch (error) {
      console.error('Erro ao salvar perfil:', error);

      res.status(500).json({
        error: 'Erro ao salvar perfil.'
      });
    }
  }
);

/* ================= PLANS ================= */

app.post(
  '/api/plans',
  async (req, res) => {
    try {
      const { name } = req.body || {};

      if (!name?.trim()) {
        return res.status(400).json({
          error: 'Nome obrigatório'
        });
      }

      const id = uid();

      await pool.query(`
        INSERT INTO workout_plans(
          id,
          name,
          sort_order
        )
        VALUES(
          $1,
          $2,
          $3
        )
      `, [
        id,
        name.trim(),
        Date.now()
      ]);

      res.json(await getState());

    } catch (error) {
      console.error('Erro ao criar treino:', error);

      res.status(500).json({
        error: 'Erro ao criar treino.'
      });
    }
  }
);

app.delete(
  '/api/plans/:id',
  async (req, res) => {
    try {
      await pool.query(
        'DELETE FROM exercises WHERE plan_id = $1',
        [req.params.id]
      );

      await pool.query(
        'DELETE FROM workout_plans WHERE id = $1',
        [req.params.id]
      );

      res.json(await getState());

    } catch (error) {
      console.error('Erro ao deletar treino:', error);

      res.status(500).json({
        error: 'Erro ao deletar treino.'
      });
    }
  }
);

/* ================= ADD EXERCISE ================= */

app.post(
  '/api/plans/:id/exercises',
  async (req, res) => {
    try {
      const e = req.body || {};

      if (!e.name?.trim()) {
        return res.status(400).json({
          error: 'Exercício obrigatório'
        });
      }

      const libResult = await pool.query(`
        SELECT
          muscle,
          instructions,
          image_url
        FROM exercises
        WHERE
          plan_id = 'LIBRARY'
          AND lower(name) = lower($1)
        LIMIT 1
      `, [e.name.trim()]);

      const lib = libResult.rows[0];

      await pool.query(`
        INSERT INTO exercises(
          id,
          plan_id,
          name,
          sets,
          reps,
          load,
          muscle,
          instructions,
          image_url
        )
        VALUES(
          $1,
          $2,
          $3,
          $4,
          $5,
          $6,
          $7,
          $8,
          $9
        )
      `, [
        uid(),
        req.params.id,
        e.name.trim(),
        Number(e.series) || 3,
        e.reps || '10',
        e.carga || '—',
        lib?.muscle || '',
        lib?.instructions || '',
        lib?.image_url || ''
      ]);

      res.json(await getState());

    } catch (error) {
      console.error('Erro ao adicionar exercício:', error);

      res.status(500).json({
        error: 'Erro ao adicionar exercício.'
      });
    }
  }
);

/* ================= DELETE EXERCISE ================= */

app.delete(
  '/api/exercises/:id',
  async (req, res) => {
    try {
      await pool.query(
        'DELETE FROM exercises WHERE id = $1',
        [req.params.id]
      );

      res.json(await getState());

    } catch (error) {
      console.error('Erro ao deletar exercício:', error);

      res.status(500).json({
        error: 'Erro ao deletar exercício.'
      });
    }
  }
);

/* ================= EDIT EXERCISE ================= */

app.put(
  '/api/exercises/:id',
  async (req, res) => {
    try {
      const e = req.body || {};

      await pool.query(`
        UPDATE exercises
        SET
          name = $1,
          sets = $2,
          reps = $3,
          load = $4
        WHERE id = $5
      `, [
        e.name,
        Number(e.series) || 3,
        e.reps || '10',
        e.carga || '—',
        req.params.id
      ]);

      res.json(await getState());

    } catch (error) {
      console.error('Erro ao editar exercício:', error);

      res.status(500).json({
        error: 'Erro ao editar exercício.'
      });
    }
  }
);

/* ================= WEIGHTS ================= */

app.post(
  '/api/weights',
  async (req, res) => {
    try {
      const { data, peso } = req.body || {};

      if (!data || !peso) {
        return res.status(400).json({
          error: 'Data e peso obrigatórios'
        });
      }

      await pool.query(`
        INSERT INTO weight_logs(
          date,
          weight
        )
        VALUES(
          $1,
          $2
        )
      `, [
        data,
        Number(peso)
      ]);

      res.json(await getState());

    } catch (error) {
      console.error('Erro ao salvar peso:', error);

      res.status(500).json({
        error: 'Erro ao salvar peso.'
      });
    }
  }
);

app.delete(
  '/api/weights/:id',
  async (req, res) => {
    try {
      await pool.query(
        'DELETE FROM weight_logs WHERE id = $1',
        [req.params.id]
      );

      res.json(await getState());

    } catch (error) {
      console.error('Erro ao deletar peso:', error);

      res.status(500).json({
        error: 'Erro ao deletar peso.'
      });
    }
  }
);

/* ================= SAVE WORKOUT ================= */

app.post(
  '/api/workouts',
  async (req, res) => {
    try {
      const w = req.body || {};

      const result = await pool.query(`
        INSERT INTO workout_sessions(
          date,
          plan_id,
          plan_name,
          duration,
          calories
        )
        VALUES(
          $1,
          $2,
          $3,
          $4,
          $5
        )
        RETURNING id
      `, [
        w.data ||
          new Date()
            .toISOString()
            .slice(0, 10),

        w.planId || null,

        w.diaNome || 'Treino',

        Number(w.duration) || 0,

        Number(w.calories) || 0
      ]);

      const sessionId = result.rows[0].id;

      for (const ex of (w.exercicios || [])) {

        for (const s of (ex.sets || [])) {

          await pool.query(`
            INSERT INTO workout_sets(
              session_id,
              exercise_name,
              set_number,
              reps,
              load,
              completed
            )
            VALUES(
              $1,
              $2,
              $3,
              $4,
              $5,
              $6
            )
          `, [
            sessionId,
            ex.nome,
            Number(s.setNumber) || 0,
            Number(s.reps) || 0,
            Number(s.carga) || 0,
            s.feito ? 1 : 0
          ]);

        }

      }

      res
        .status(201)
        .json(await getState());

    } catch (error) {

      console.error(
        'Erro ao salvar treino:',
        error
      );

      res.status(500).json({
        error: 'Erro ao salvar o treino.'
      });
    }
  }
);

/* ================= EXERCISE HISTORY ================= */

app.get(
  '/api/workouts/:exercise',
  async (req, res) => {
    try {
      const name = decodeURIComponent(
        req.params.exercise
      );

      const result = await pool.query(`
        SELECT
          ws.date,
          ws.plan_name AS "diaNome",
          wset.set_number,
          wset.reps,
          wset.load AS carga
        FROM workout_sets wset
        JOIN workout_sessions ws
          ON ws.id = wset.session_id
        WHERE
          lower(wset.exercise_name) = lower($1)
          AND wset.completed = 1
        ORDER BY
          ws.date DESC,
          wset.set_number
      `, [name]);

      res.json(result.rows);

    } catch (error) {
      console.error(
        'Erro ao buscar histórico:',
        error
      );

      res.status(500).json({
        error: 'Erro ao buscar histórico.'
      });
    }
  }
);

/* ================= FRONTEND ================= */

app.use(
  (req, res) => {

    res.sendFile(
      path.join(
        __dirname,
        'public',
        'index.html'
      )
    );

  }
);

/* ================= START SERVER ================= */

initDatabase()
  .then(() => {
    app.listen(
      PORT,
      () => {
        console.log(
          `GYM TRACKER rodando em http://localhost:${PORT}`
        );
      }
    );
  })
  .catch(error => {
    console.error(
      'Erro ao inicializar PostgreSQL:',
      error
    );
  });